query Articles {
  articles {
    id
    title
    copy
    cover {
      url
    }
    date_of_pub
    category {
      name
    }
    content {
      ... on ComponentBlogParagraphe {
        copy
      }
      ... on ComponentBlogImages {
        images {
          url
        }
      }
      ... on ComponentBlogLien {
        link {
          link
        }
      }
      ... on ComponentBlogQuote {
        quote
        author
      }
    }
  }
}